# S4 Configuration
s4:
  type: "s4"
  d_model: 256
  d_state: 64
  dropout: 0.1
  bidirectional: false
  dt_min: 0.001
  dt_max: 0.1

# S5 Configuration
s5:
  type: "s5"
  d_model: 256
  d_state: 64
  dropout: 0.1
  dt_min: 0.001
  dt_max: 0.1
  init_scale: 1.0

# Mamba Configuration
mamba:
  type: "mamba"
  d_model: 256
  d_state: 16
  dropout: 0.1
  expansion_factor: 2
  conv_kernel: 4
  num_blocks: 4
  max_seq_len: 2048

# Mamba2 Configuration
mamba2:
  type: "mamba2"
  d_model: 256
  d_state: 64
  dropout: 0.1
  d_conv: 4
  expand_factor: 2
  conv_kernel_size: 4
  num_layers: 4
  max_seq_len: 2048
  block_type: "sequential"  # one of: "sequential", "parallel"
  selective_scan: true

# S4D Configuration
s4d:
  type: "s4d"
  d_model: 256
  d_state: 64
  dropout: 0.0
  dt_min: 0.001
  dt_max: 0.1
  init_method: "inv"  # one of: "inv", "lin", "legs"
  real_transform: true 

# Transformer Configuration
transformer:
  type: "transformer"
  d_model: 256
  nhead: 8
  num_layers: 4
  dim_feedforward: 1024
  dropout: 0.1
  activation: "gelu"
  max_seq_len: 2048
  layer_norm_eps: 1e-5
  batch_first: true
  norm_first: true 